# Utilisation de l'image de base avec Uvicorn, Gunicorn, FastAPI sur Python 3.10
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

# Définition du répertoire de travail dans le conteneur
WORKDIR /app

# Copie des fichiers de l'API IA dans le conteneur
COPY . /app/api_ia

# Installer les dépendances système requises
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    unixodbc \
    unixodbc-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Add SQL Server ODBC Driver 17 for Ubuntu 18.04
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
  && apt-get update \
  && apt-get install -y --no-install-recommends --allow-unauthenticated msodbcsql17 mssql-tools \
  && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile \
  && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

# Installation des dépendances Python
RUN pip install --no-cache-dir --upgrade -r api_ia/api/requirements.txt

# Commande pour lancer l'application
CMD ["uvicorn", "api_ia.api.main:app", "--host", "0.0.0.0", "--port", "8001"]
