version: '3.8'

services:
  
  api_database:
    build: ./api_database
    image: manon29/api_database:latest
    ports:
      - 8000:8000
    

  api_ia:
    build: ./api_ia
    image: manon29/api_ia:latest
    ports:
     - 8001:8001
