site_name: Problem management

theme:
  name: "material"

plugins:
 - mkdocstrings

nav: 
  - Home: index.md
  - API BDD: 
    - Database : 
      - authentication: api_bdd/database_authentication.md
      - incidents: api_bdd/database_incidents.md
      - core: api_bdd/database_core.md
    - Routers:
      - authentication: api_bdd/router_authentication.md
      - incidents: api_bdd/router_incidents.md 
