# Utilisation d'une image de base Python
FROM python:3.10

# Définition du répertoire de travail dans le conteneur
WORKDIR /app

ENV PYTHONUNBUFFERED 1
# définit une variable d'environnement

# Copie des fichiers de l'API FastAPI dans le conteneur
COPY . /app/api_database

ENV ACCEPT_EULA=Y
RUN apt-get update -y && apt-get update \
  && apt-get install -y --no-install-recommends curl gcc g++ gnupg unixodbc-dev

# Add SQL Server ODBC Driver 17 for Ubuntu 18.04
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list \
  && apt-get update \
  && apt-get install -y --no-install-recommends --allow-unauthenticated msodbcsql17 mssql-tools \
  && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile \
  && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

# Installation des dépendances Python
RUN pip install --upgrade pip && pip install -r api_database/api/requirements.txt

# Commande pour démarrer l'API avec uvicorn
CMD ["uvicorn", "api_database.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
