defaults:
    - _self_
    - model: kmeans


project_name: datascience_problem_management
model_name: ${hydra:runtime.output_dir}/model-${project_name}


# monitoring:
#     run_name: ${project_name}-${now:%Y-%m-%d_%H-%M-%S}

hydra:
    job:
        chdir: false
    run:
        dir: outputs/hydra/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
        dir: outputs/hydra/${now:%Y-%m-%d_%H-%M-%S}
        subdir: ${hydra.job.override_dirname}