
name: CI 

on:
  push:
    branches:
    - main 

jobs: 
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2 

      - name: Set up Python 
        uses: actions/setup-python@v2
        with: 
          python-version: '3.10'

      - name: Install requirements 
        run: pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "API_IA_SECRET_KEY=${{ secrets.API_IA_SECRET_KEY }}" >> $GITHUB_ENV &&
          echo "AZURE_DATABASE_NAME=${{ secrets.AZURE_DATABASE_NAME }}" >> $GITHUB_ENV &&
          echo "AZURE_DATABASE_PASSWORD=${{ secrets.AZURE_DATABASE_PASSWORD }}" >> $GITHUB_ENV &&
          echo "AZURE_DATABASE_USERNAME=${{ secrets.AZURE_DATABASE_USERNAME }}" >> $GITHUB_ENV &&
          echo "AZURE_SERVER_NAME=${{ secrets.AZURE_SERVER_NAME }}" >> $GITHUB_ENV &&
          echo "DRIVER=${{ secrets.DRIVER }}" >> $GITHUB_ENV &&
          echo "EMBEDDING_API_KEY=${{ secrets.EMBEDDING_API_KEY }}" >> $GITHUB_ENV &&
          echo "EMBEDDING_AZURE_DEPLOYMENT=${{ secrets.EMBEDDING_AZURE_DEPLOYMENT }}" >> $GITHUB_ENV &&
          echo "EMBEDDING_AZURE_ENDPOINT=${{ secrets.EMBEDDING_AZURE_ENDPOINT }}" >> $GITHUB_ENV &&
          echo "EMBEDDING_OPENAI_API_VERSION=${{ secrets.EMBEDDING_OPENAI_API_VERSION }}" >> $GITHUB_ENV &&
          echo "NAMING_OPENAI_API_BASE=${{ secrets.NAMING_OPENAI_API_BASE }}" >> $GITHUB_ENV &&
          echo "NAMING_OPENAI_API_KEY=${{ secrets.NAMING_OPENAI_API_KEY }}" >> $GITHUB_ENV &&
          echo "NAMING_OPENAI_API_TYPE=${{ secrets.NAMING_OPENAI_API_TYPE }}" >> $GITHUB_ENV &&
          echo "API_DATABASE_SECRET_KEY=${{ secrets.API_DATABASE_SECRET_KEY }}" >> $GITHUB_ENV &&
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI}}" $GITHUB_ENV

      

      - name: Run Test 
        run: pytest -v

        